# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 239169e0af103a1f4aec3df92f8d2406417c1b1f0c732876cd26f3c25eb4593cc30a84e4a3269af4817abe751f0b24a13b3b0d6b7a4f6986851bbcdca9e351ec

test:
  secret_key_base: 9bc4a49a1a51a9b06e6494035887b978f7597cdf9ffee901398f07a5af016e49e46ab196a8412e9730471ac017c5c739f95a0b4f8cb436c524891a0455305684

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
